### ISSUE TITLE
rough breakdown of responsibilities

### ISSUE THREAD

**Issue by awyand** [awyand/spiffy-plus#5]
Aaron
----
 - Twitter API
 - Image upload API / hosting
 - GitHub Management / Clean Up / Project Board Maintenance

Henry
 ----
- Google Maps API
- Good Place API (for autofill location in user form)

Hillary
----
 - Front End Design / UI
 - Application Structure / MVC / Handlebars
 - MySQL Schema and Tables / Sequelize

Jeremy
----
 - Node Server / Express App
 - API Front End (jQuery logic, making API requests, handling API responses)
 - API Back End (routes, handling API requests, sending API responses) 

All
----
 - Documentation

Unclaimed
----
 - Google Authentication
 - Node Server / Express App
 - API Front End (jQuery logic, making API requests, handling API responses)
 - API Back End (routes, handling API requests, sending API responses)

**Comment by Henryhankdc** [comment]
I want all the googlymaps/map stuff

**Comment by awyand** [comment]
updated

**Comment by awyand** [comment]
more or less done, closing this one.
